### ISSUE TITLE
Wiki tutorial edit: Eigengrasp Planner Example and GraspIt API ROS Wrapper

### ISSUE THREAD

**Issue by saspelund** [JenniferBuehler/graspit-pkgs#10]
For the Eigengrasp Planner Example and GraspIt API ROS Wrapper tutorials, in the Inspect the Results section, the instructions say to run the command `rosrun graspit graspit_simulator`. This returns error `[rospack] Error: package 'graspit' not found`. I looked at the subsequently mentioned tutorial for the GraspIt! simulator and ran `rosrun grasp_planning_graspit graspit_simulator_standalone` instead, which was successful. I was then able to open up the world files of the results from there.

My comprehension of what I am doing is still minimal so please feel free to correct me if I am wrong. I was able to reproduce each of the other steps in the tutorial. Thanks for the tutorials!

P.S. Is there a Q/A location for asking general-use questions of this program; should I open issues or email you through your site? And what is the best way to know when I should re-clone your latest updates to my local storage (i.e. seg fault fixes vs wiki edits)? Thank you for your time!

**Comment by JenniferBuehler** [comment]
Hi,
thanks for pointing out the error in the wiki. I fixed it. This happened because graspit_simulator is actually also built when building graspit separately with ROS, but that's not the standard way it's done, so the error must have snug in while I was on another testing setup.

As for the Q/A location: Just use the issues here, there's no separate Q/A section.

The wiki pages and the code repository are separate. So you would only need to keep the source repository up-to-date. The safest bet is to do regular `git pull`, as I'm still actively working on the packages. However there won't be many more frequent changes starting from mid-next week.

Hope this helped. Closing this issue, if there's any other questions you have, just re-open it.

Have a nice weekend
Jenny
