### ISSUE TITLE
Unable to use my urdf with graspit

### ISSUE THREAD

**Issue by gstavrinos** [JenniferBuehler/graspit-pkgs#36]
Hello Jennifer,

I am trying to integrate our gripper (Schunk PG70) with graspit using your `graspit-pkgs`. I am using the `urdf_viewer` to view my `.urdf`, and when I am happy with how it looks, I convert it to `.xml` using your `urdf2graspit_node`. Everything seems fine as I am able to import my robot in the `graspit_interface`. When I import an object and then try to plan some grasps though, the interface does nothing for a bit, as if it's planning, which is normal, and then the gripper turns and the fingers get stuck in the main body. At that point I get the `LCP could not be solved.` message. You can see the problem in the screenshots below.

Before:

![graspit_interface_before](https://user-images.githubusercontent.com/6703819/46203202-c1596b00-c321-11e8-96b6-43ee7eb6ef7c.png)

After:

![graspit_interface_after](https://user-images.githubusercontent.com/6703819/46203196-bb638a00-c321-11e8-82df-421ae95106dc.png)
You can view my files here:
https://github.com/Roboskel-Manipulation/manos_graspit_config/tree/master/schunk_pg70

Thanks in advance for any kind of help.

George

**Comment by JenniferBuehler** [comment]
Hi George,

thanks for posting about this issue. Quick question in advance: have you generated contact points for the robot hand, as described [here](https://github.com/JenniferBuehler/graspit-pkgs/wiki/Conversion-with-urdf2graspit#step-2-optional-choose-your-contact-points-in-the-viewer) in the tutorial? I can't see the contact points on the screenshot. Contact points are important for planning.

If you open the files with the original `graspit_simulator` (are you using the newest version from their repo?), the contact points should be displayed as well. It may be that the contact points generator needs some updates, since the original graspit source has been updated. If you cannot see the contact points, maybe you can try to generate them using the approach described in [this issue](https://github.com/graspit-simulator/graspit/issues/126#issuecomment-325983510) instead, and see if it works then. I would love to hear if that made a difference.

Regards
Jennifer

**Comment by gstavrinos** [comment]
Hey,

Thanks for the answer. The images are from an older version. I have now created the contact points (manually because I experience some crashes related to Eigen). The EIgengrap planners work like a charm, but using the dynamics (From the "play" button that starts the simulation) still causes the effect depicted above.

It is not a major issue, I just want to be sure that my URDF is not problematic.

THanks for your time,

George

**Comment by JenniferBuehler** [comment]
What I can imagine could be not ideal are the contact points. I'm aware that I need to update the contact points generator, I just keep not getting around to it :/

If the robot looks OK in the simulator, then the graspit files should have been converted alright from URDF, because if it didn't work, you would definitely notice it, some links would be totally off.

Did you already ask about this issue on the graspit github? Maybe they can help you better in pinpointing why this happens.

**Comment by gstavrinos** [comment]
The robot looks fine on the simulator, so I guess I can trust the Eigen planning.

Just as you suggested, I will open an issue on the graspit repository.

Finally, if there are any specific features you plan to implement for the contact points generator, please open some issues so the community (me included) can work on them.

Thank you for your assistance. I will close this issue for now :)

**Comment by JenniferBuehler** [comment]
Good point, I've written down my thoughts on what needs doing in issue #37.

**Comment by JenniferBuehler** [comment]
Good point, I've written down my thoughts on what needs doing in issue #37.
