### ISSUE TITLE
urdf2graspit package, always error to load the generated robot file.

### ISSUE THREAD

**Issue by majiqiang** [JenniferBuehler/graspit-pkgs#52]
I use the package to generate robot.xml file, but when I load the robot file and object file to graspit , I met the error as the following picture.
![pic](https://user-images.githubusercontent.com/37575460/60674035-c8626a80-9eab-11e9-8a6d-0f333fda5252.png)

**Comment by JenniferBuehler** [comment]
Hi, as far as I can see this wouldn't have to do with the model itself, or maybe it could be related to the contact points or eigengrasps you defined, but I think the model itself would not be the issue (otherwise you'd visually see that something is wrong). I see you already have [the same issue](https://github.com/graspit-simulator/graspit/issues/159) on the graspit repo, maybe someone will be able to recognise this behaviour and give you a hint where it comes from. It probably helps if you describe the issue in more detail, e.g. are you running into an endless loop, or what is happening. 

I'll close this issue, it's better to have only one issue about the same topic.
